# Generated by Django 5.2.8 on 2025-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='project_link',
            field=models.URLField(blank=True, help_text='GitHub or live project link'),
        ),
    ]
