# Generated by Django 5.2.8 on 2025-12-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freelancerprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='years_of_experience',
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_skills', to='accounts.freelancerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
            ],
        ),
    ]
