# Generated by Django 5.2.8 on 2025-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_remove_freelancerprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
